# Generated by Django 4.1.3 on 2023-03-29 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_user_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='ForumUser',
        ),
    ]
