# Generated by Django 4.1.3 on 2023-03-30 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_forumuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
